# Training/Test set

In [5]:
import tensorflow as tf

x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

In [6]:
X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,3])
W = tf.Variable(tf.random_normal([3,3]), name='weight')
b = tf.Variable(tf.random_normal([3]), name='bias')

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Correct prediction Test model
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch the graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X:x_data, Y:y_data})
        print(step, cost_val, W_val)
    
    # predict
    print("Prediction : ", sess.run(prediction, feed_dict={X:x_test}))
    # accuracy
    print("Accuracy : ", sess.run(accuracy, feed_dict={X:x_test, Y:y_test}))
    

0 6.921978 [[-0.34420124 -1.8207142  -0.12573427]
 [ 0.08537128  0.05464277 -1.8231264 ]
 [-1.1955417   0.4323903  -0.46635452]]
1 4.812258 [[-0.32103077 -1.8808647  -0.08875427]
 [ 0.2438317  -0.2027385  -1.7242056 ]
 [-1.0352896   0.18526918 -0.37948552]]
2 2.7991672 [[-0.30384377 -1.9339858  -0.05282017]
 [ 0.38428107 -0.43978906 -1.6276044 ]
 [-0.8876472  -0.04710893 -0.2947498 ]]
3 1.5486813 [[-0.32499534 -1.9456648  -0.01998967]
 [ 0.3251382  -0.47007355 -1.538177  ]
 [-0.9165871  -0.09125988 -0.22165895]]
4 1.3264376 [[-0.34320235 -1.9560881   0.00864068]
 [ 0.2781689  -0.50235456 -1.4589267 ]
 [-0.9344598  -0.13109851 -0.16394766]]
5 1.173268 [[-0.35987076 -1.9623232   0.03154425]
 [ 0.23476529 -0.5231969  -1.3946807 ]
 [-0.94931316 -0.15238027 -0.12781249]]
6 1.0875554 [[-0.37283868 -1.9667535   0.04894246]
 [ 0.2071617  -0.54359156 -1.3466824 ]
 [-0.9496015  -0.16755359 -0.11235084]]
7 1.0464437 [[-0.38442868 -1.9681535   0.06193249]
 [ 0.18360297 -0.5534992  -1.3132161 ]
 [-

121 0.62524587 [[-1.0189029  -1.967338    0.69559115]
 [-0.3658503  -0.61505806 -0.70220363]
 [-0.1435669  -0.13401385 -0.95192504]]
122 0.62435156 [[-1.02335    -1.9670206   0.6997209 ]
 [-0.36682823 -0.6147201  -0.70156366]
 [-0.1408275  -0.13431823 -0.95436007]]
123 0.6234646 [[-1.0277885  -1.9666989   0.70383763]
 [-0.3677804  -0.6143864  -0.70094526]
 [-0.13811797 -0.13462017 -0.9567677 ]]
124 0.62258506 [[-1.0322185  -1.9663727   0.7079414 ]
 [-0.36870775 -0.61405647 -0.7003478 ]
 [-0.13543795 -0.13491943 -0.95914847]]
125 0.6217128 [[-1.0366399  -1.9660423   0.7120324 ]
 [-0.36961058 -0.61373067 -0.69977075]
 [-0.13278645 -0.13521644 -0.96150297]]
126 0.6208475 [[-1.0410529  -1.9657075   0.7161106 ]
 [-0.37048984 -0.61340845 -0.6992137 ]
 [-0.13016316 -0.13551085 -0.96383184]]
127 0.61998904 [[-1.0454574  -1.9653686   0.72017616]
 [-0.37134573 -0.6130902  -0.698676  ]
 [-0.12756705 -0.13580325 -0.96613556]]
128 0.61913717 [[-1.0498534  -1.9650255   0.7242292 ]
 [-0.37217933 -0.6

# Big learning rate

In [7]:
X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,3])
W = tf.Variable(tf.random_normal([3,3]), name='weight')
b = tf.Variable(tf.random_normal([3]), name='bias')

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1.5).minimize(cost)

# Correct prediction Test model
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch the graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X:x_data, Y:y_data})
        print(step, cost_val, W_val)
    
    # predict
    print("Prediction : ", sess.run(prediction, feed_dict={X:x_test}))
    # accuracy
    print("Accuracy : ", sess.run(accuracy, feed_dict={X:x_test, Y:y_test}))

0 6.632794 [[ 0.4928637  -1.4864905  -0.94068223]
 [ 2.441493   -4.0612245   0.55021375]
 [ 1.4081042  -2.9355216  -0.17546272]]
1 23.226044 [[-0.6313178  -0.9239905  -0.37900072]
 [-1.6818442  -1.4362245   2.048551  ]
 [-2.7160442  -0.1230216   1.1361855 ]]
2 21.950668 [[-0.25631788 -0.3615104  -1.3164806 ]
 [ 0.7556555   1.1887355  -3.0139084 ]
 [-0.2785442   2.6894577  -4.1137934 ]]
3 17.134869 [[ 0.11840475 -1.298733   -0.75398064]
 [ 3.192592   -2.748201   -1.5139085 ]
 [ 2.1586692  -1.0602558  -2.8012934 ]]
4 25.060349 [[-1.0065949  -0.7362331  -0.19148093]
 [-0.93240714 -0.12320113 -0.0139091 ]
 [-1.9663303   1.7522438  -1.4887937 ]]
5 10.614988 [[-0.6316203  -1.6520079   0.34931922]
 [ 1.5050418  -4.016238    1.4416795 ]
 [ 0.47114396 -1.9750154  -0.19900858]]
6 14.632747 [[-0.62606263 -1.0895079  -0.21873844]
 [ 1.887414   -1.3912382  -1.5656924 ]
 [ 0.81988376  0.8374846  -3.360248  ]]
7 10.725235 [[-1.7467132  -0.531255    0.34365916]
 [-2.2287312   1.2251115  -0.06589735]
 

Prediction :  [0 0 0]
Accuracy :  0.0


# Small learning rate

In [8]:
X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,3])
W = tf.Variable(tf.random_normal([3,3]), name='weight')
b = tf.Variable(tf.random_normal([3]), name='bias')

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-10).minimize(cost)

# Correct prediction Test model
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch the graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X:x_data, Y:y_data})
        print(step, cost_val, W_val)
    
    # predict
    print("Prediction : ", sess.run(prediction, feed_dict={X:x_test}))
    # accuracy
    print("Accuracy : ", sess.run(accuracy, feed_dict={X:x_test, Y:y_test}))

0 2.9345984 [[ 0.53219664 -0.04326498 -0.3540067 ]
 [ 0.38889655  1.7420006   0.10040051]
 [ 1.6471255  -0.85674876  0.5065184 ]]
1 2.9345984 [[ 0.53219664 -0.04326498 -0.3540067 ]
 [ 0.38889655  1.7420006   0.10040051]
 [ 1.6471255  -0.85674876  0.5065184 ]]
2 2.9345984 [[ 0.53219664 -0.04326498 -0.3540067 ]
 [ 0.38889655  1.7420006   0.10040051]
 [ 1.6471255  -0.85674876  0.5065184 ]]
3 2.9345984 [[ 0.53219664 -0.04326498 -0.3540067 ]
 [ 0.38889655  1.7420006   0.10040051]
 [ 1.6471255  -0.85674876  0.5065184 ]]
4 2.9345984 [[ 0.53219664 -0.04326498 -0.3540067 ]
 [ 0.38889655  1.7420006   0.10040051]
 [ 1.6471255  -0.85674876  0.5065184 ]]
5 2.9345984 [[ 0.53219664 -0.04326498 -0.3540067 ]
 [ 0.38889655  1.7420006   0.10040051]
 [ 1.6471255  -0.85674876  0.5065184 ]]
6 2.9345984 [[ 0.53219664 -0.04326498 -0.3540067 ]
 [ 0.38889655  1.7420006   0.10040051]
 [ 1.6471255  -0.85674876  0.5065184 ]]
7 2.9345984 [[ 0.53219664 -0.04326498 -0.3540067 ]
 [ 0.38889655  1.7420006   0.10040051]


118 2.9345984 [[ 0.53219664 -0.04326498 -0.3540067 ]
 [ 0.38889655  1.7420006   0.10040051]
 [ 1.6471255  -0.85674876  0.5065184 ]]
119 2.9345984 [[ 0.53219664 -0.04326498 -0.3540067 ]
 [ 0.38889655  1.7420006   0.10040051]
 [ 1.6471255  -0.85674876  0.5065184 ]]
120 2.9345984 [[ 0.53219664 -0.04326498 -0.3540067 ]
 [ 0.38889655  1.7420006   0.10040051]
 [ 1.6471255  -0.85674876  0.5065184 ]]
121 2.9345984 [[ 0.53219664 -0.04326498 -0.3540067 ]
 [ 0.38889655  1.7420006   0.10040051]
 [ 1.6471255  -0.85674876  0.5065184 ]]
122 2.9345984 [[ 0.53219664 -0.04326498 -0.3540067 ]
 [ 0.38889655  1.7420006   0.10040051]
 [ 1.6471255  -0.85674876  0.5065184 ]]
123 2.9345984 [[ 0.53219664 -0.04326498 -0.3540067 ]
 [ 0.38889655  1.7420006   0.10040051]
 [ 1.6471255  -0.85674876  0.5065184 ]]
124 2.9345984 [[ 0.53219664 -0.04326498 -0.3540067 ]
 [ 0.38889655  1.7420006   0.10040051]
 [ 1.6471255  -0.85674876  0.5065184 ]]
125 2.9345984 [[ 0.53219664 -0.04326498 -0.3540067 ]
 [ 0.38889655  1.742000

# Non-normalized data

In [19]:
import numpy as np

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([4,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
    print(step, "Cost: ", cost_val, "\nPrediction: \n", hy_val)

2000 Cost:  nan 
Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]


# Normalized data ( min-max scale)

### Sklearn Library 사용

In [21]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0,1))
xy = scaler.fit_transform(xy)
print(xy)

[[1.         1.         0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881783 0.83755792]
 [0.54412549 0.50274824 0.57608696 0.60646801 0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.4258239  0.30434783 0.58504805 0.42624401]
 [0.49556179 0.4258239  0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


### MinMaxScaler 함수 정의하여 사용

In [22]:
def MinMaxScaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

In [23]:
xy = MinMaxScaler(xy)
print(xy)

[[0.9999999  0.9999999  0.         0.9999999  0.9999999 ]
 [0.70548484 0.70439545 0.9999999  0.71881775 0.83755783]
 [0.54412544 0.50274819 0.5760869  0.60646794 0.66063303]
 [0.33890349 0.3136802  0.10869564 0.4598913  0.43800914]
 [0.51435995 0.42582385 0.3043478  0.585048   0.42624397]
 [0.49556174 0.42582385 0.31521736 0.48131129 0.49276132]
 [0.11436063 0.         0.20652172 0.22007774 0.18597236]
 [0.         0.07747099 0.53260864 0.         0.        ]]


In [24]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([4,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
    print(step, "Cost: ", cost_val, "\nPrediction: \n", hy_val)

2000 Cost:  0.109844536 
Prediction: 
 [[ 1.080426  ]
 [ 1.059934  ]
 [ 0.5458162 ]
 [-0.03296906]
 [ 0.3302685 ]
 [ 0.29675347]
 [-0.439185  ]
 [-0.38649875]]
