# Multi Variable Regression

In [4]:
import tensorflow as tf
# Data
x1_data = [73.,93.,89.,96.,73.]
x2_data = [80.,88.,91.,98.,66.]
x3_data = [75.,93.,90.,100.,70.]
y_data = [152.,185.,180.,196.,142.]
# Placeholder
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)
# Vaiables
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')
# Hypothesis
hypothesis = x1*w1 + x2*w2 + x3*w3 + b


In [5]:
# Cost/Loss Function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize : Gradient Descent 
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Session start
sess = tf.Session()
# initialize variables
sess.run(tf.global_variables_initializer())
# run
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {x1:x1_data, x2:x2_data, x3:x3_data, Y:y_data})
    
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val )

0 Cost:  67834.33 
Prediction:
 [ -77.70052   -94.32473   -92.29841  -102.320625  -70.709564]
10 Cost:  2.0375392 
Prediction:
 [152.69154 182.59705 180.55331 194.80875 140.51338]
20 Cost:  1.4107492 
Prediction:
 [153.38452 183.4377  181.3776  195.70702 141.15593]
30 Cost:  1.40496 
Prediction:
 [153.38255 183.44301 181.37881 195.70905 141.16135]
40 Cost:  1.39921 
Prediction:
 [153.37848 183.44579 181.37755 195.70831 141.16481]
50 Cost:  1.393481 
Prediction:
 [153.37442 183.44855 181.37627 195.70761 141.16827]
60 Cost:  1.387791 
Prediction:
 [153.37038 183.45131 181.375   195.7069  141.17172]
70 Cost:  1.3821242 
Prediction:
 [153.36632 183.45406 181.37373 195.70616 141.17516]
80 Cost:  1.3765066 
Prediction:
 [153.3623  183.45679 181.37247 195.70547 141.17857]
90 Cost:  1.3709157 
Prediction:
 [153.35829 183.45952 181.37122 195.70476 141.18199]
100 Cost:  1.3653346 
Prediction:
 [153.35426 183.46225 181.36996 195.70406 141.1854 ]
110 Cost:  1.3597867 
Prediction:
 [153.35028 183.4

 [153.03368 183.68019 181.26935 195.64954 141.45605]
1010 Cost:  0.964639 
Prediction:
 [153.03052 183.68233 181.26837 195.64902 141.4587 ]
1020 Cost:  0.96121454 
Prediction:
 [153.02739 183.6845  181.2674  195.6485  141.46135]
1030 Cost:  0.9578177 
Prediction:
 [153.02426 183.68661 181.26639 195.64798 141.46396]
1040 Cost:  0.954435 
Prediction:
 [153.02112 183.68872 181.2654  195.64749 141.46657]
1050 Cost:  0.95107985 
Prediction:
 [153.018   183.69084 181.26442 195.64696 141.46918]
1060 Cost:  0.9477291 
Prediction:
 [153.0149  183.69296 181.26344 195.64645 141.47179]
1070 Cost:  0.9444046 
Prediction:
 [153.0118  183.69508 181.26248 195.64595 141.47438]
1080 Cost:  0.9410861 
Prediction:
 [153.0087  183.69717 181.26149 195.64545 141.47699]
1090 Cost:  0.9378077 
Prediction:
 [153.00562 183.69925 181.26051 195.64494 141.47955]
1100 Cost:  0.93451995 
Prediction:
 [153.00253 183.70135 181.25954 195.64445 141.48212]
1110 Cost:  0.93127394 
Prediction:
 [152.99947 183.70343 181.2585

 [152.75626 183.86838 181.18176 195.606   141.68636]


### 이러한 방법은 쓰지 않는다. => Martix 를 이용한 방법

In [10]:
# Matrix Form
x_data = [[73.,80.,75.], [93.,88.,93.], [89.,91.,90.], [96.,98.,100.], [73.,66.,70.]]
y_data = [[152.],[185.],[180.],[196.],[142.]]
# placeholder
X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

In [19]:
# Cost/Loss Function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize : Gradient Descent 
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Session start
sess = tf.Session()
# initialize variables
sess.run(tf.global_variables_initializer())
# run
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {X:x_data, Y:y_data})
    
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val )

0 Cost:  7855.6274 
Prediction:
 [[66.9619  ]
 [85.09745 ]
 [81.25945 ]
 [91.837814]
 [63.149765]
 [51.97072 ]
 [72.20036 ]
 [58.28623 ]
 [84.53534 ]
 [85.90582 ]
 [67.502686]
 [69.785774]
 [80.68866 ]
 [62.567444]
 [73.5679  ]
 [89.07847 ]
 [56.959995]
 [87.81536 ]
 [75.682   ]
 [67.758644]
 [84.25635 ]
 [82.71003 ]
 [78.985054]
 [59.86811 ]
 [85.96572 ]]
10 Cost:  19.671186 
Prediction:
 [[149.63312]
 [184.44064]
 [179.15489]
 [198.44516]
 [138.91692]
 [107.81575]
 [151.9931 ]
 [117.43109]
 [177.36395]
 [171.86777]
 [144.38135]
 [145.57777]
 [181.83624]
 [146.6611 ]
 [153.72353]
 [189.88248]
 [137.0519 ]
 [183.57391]
 [172.11613]
 [154.04489]
 [177.82605]
 [175.90053]
 [168.20044]
 [143.23926]
 [188.93045]]
20 Cost:  19.183142 
Prediction:
 [[150.21762 ]
 [185.12314 ]
 [179.83836 ]
 [199.18143 ]
 [139.43912 ]
 [108.18591 ]
 [152.53784 ]
 [117.826546]
 [177.98727 ]
 [172.42545 ]
 [144.90848 ]
 [146.08559 ]
 [182.55028 ]
 [147.26488 ]
 [154.26686 ]
 [190.5692  ]
 [137.63052 ]
 [184.227

230 Cost:  17.00518 
Prediction:
 [[150.48965]
 [185.0512 ]
 [179.98636]
 [199.18073]
 [139.4186 ]
 [107.87415]
 [152.40826]
 [117.56197]
 [177.6296 ]
 [171.70045]
 [144.83102]
 [145.77106]
 [182.86208]
 [147.7288 ]
 [154.05919]
 [190.3787 ]
 [138.14519]
 [184.06194]
 [173.18565]
 [155.01627]
 [178.31335]
 [176.3341 ]
 [168.749  ]
 [144.49261]
 [189.70917]]
240 Cost:  16.911077 
Prediction:
 [[150.50175]
 [185.04778]
 [179.99286]
 [199.18044]
 [139.41757]
 [107.85994]
 [152.40215]
 [117.54973]
 [177.61322]
 [171.66742]
 [144.82732]
 [145.75667]
 [182.87599]
 [147.7497 ]
 [154.04956]
 [190.36986]
 [138.16843]
 [184.05415]
 [173.20288]
 [155.03227]
 [178.30623]
 [176.32486]
 [168.74583]
 [144.52168]
 [189.7119 ]]
250 Cost:  16.817804 
Prediction:
 [[150.51381 ]
 [185.04437 ]
 [179.99931 ]
 [199.18016 ]
 [139.41656 ]
 [107.8458  ]
 [152.39607 ]
 [117.537544]
 [177.59694 ]
 [171.63457 ]
 [144.82365 ]
 [145.74232 ]
 [182.88986 ]
 [147.7705  ]
 [154.03996 ]
 [190.36107 ]
 [138.19157 ]
 [184.

480 Cost:  14.881992 
Prediction:
 [[150.7758  ]
 [184.97113 ]
 [180.14037 ]
 [199.1737  ]
 [139.3962  ]
 [107.53822 ]
 [152.26193 ]
 [117.268845]
 [177.24278 ]
 [170.91785 ]
 [144.74309 ]
 [145.43019 ]
 [183.19276 ]
 [148.22514 ]
 [153.82948 ]
 [190.17003 ]
 [138.6985  ]
 [183.87433 ]
 [173.59402 ]
 [155.39577 ]
 [178.14317 ]
 [176.11545 ]
 [168.67252 ]
 [145.18204 ]
 [189.77516 ]]
490 Cost:  14.8063135 
Prediction:
 [[150.78654]
 [184.96817]
 [180.14618]
 [199.17343]
 [139.39543]
 [107.5256 ]
 [152.25635]
 [117.25765]
 [177.22824]
 [170.88834]
 [144.73976]
 [145.41734]
 [183.20526]
 [148.24391]
 [153.82077]
 [190.16219]
 [138.71947]
 [183.86714]
 [173.60944]
 [155.41008]
 [178.13669]
 [176.10722]
 [168.66956]
 [145.20805]
 [189.7777 ]]
500 Cost:  14.731274 
Prediction:
 [[150.79726 ]
 [184.96521 ]
 [180.15195 ]
 [199.17314 ]
 [139.39467 ]
 [107.51302 ]
 [152.25078 ]
 [117.246506]
 [177.21376 ]
 [170.85896 ]
 [144.73643 ]
 [145.40456 ]
 [183.2177  ]
 [148.26259 ]
 [153.81207 ]
 [190.1

740 Cost:  13.112798 
Prediction:
 [[151.03937]
 [184.89934]
 [180.28328]
 [199.16637]
 [139.37923]
 [107.22853]
 [152.12285]
 [116.99052]
 [176.88622]
 [170.1923 ]
 [144.66066]
 [145.11484]
 [183.50066]
 [148.68813]
 [153.61366]
 [189.97765]
 [139.21681]
 [183.6946 ]
 [173.97333]
 [155.74756]
 [177.98238]
 [175.91371]
 [168.59863]
 [145.82207]
 [189.83865]]
750 Cost:  13.052404 
Prediction:
 [[151.04889]
 [184.89679]
 [180.28848]
 [199.1661 ]
 [139.37871]
 [107.21736]
 [152.11775]
 [116.98032]
 [176.87338]
 [170.1661 ]
 [144.65768]
 [145.10347]
 [183.51184]
 [148.70496]
 [153.6058 ]
 [189.97073]
 [139.23569]
 [183.68799]
 [173.98708]
 [155.76028]
 [177.97653]
 [175.90646]
 [168.59593]
 [145.84525]
 [189.841  ]]
760 Cost:  12.992539 
Prediction:
 [[151.05833]
 [184.89426]
 [180.29364]
 [199.16582]
 [139.37817]
 [107.20625]
 [152.11267]
 [116.97016]
 [176.86058]
 [170.13997]
 [144.6547 ]
 [145.09212]
 [183.52295]
 [148.72166]
 [153.59796]
 [189.9638 ]
 [139.25446]
 [183.6814 ]
 [174.000

1000 Cost:  11.700902 
Prediction:
 [[151.27216]
 [184.83783]
 [180.4106 ]
 [199.15907]
 [139.36781]
 [106.95478]
 [151.9959 ]
 [116.73672]
 [176.57112]
 [169.54716]
 [144.58652]
 [144.8351 ]
 [183.77576]
 [149.10263]
 [153.41898]
 [189.80762]
 [139.68292]
 [183.52925]
 [174.31136]
 [156.0604 ]
 [177.83658]
 [175.7353 ]
 [168.53017]
 [146.3921 ]
 [189.89735]]
1010 Cost:  11.652715 
Prediction:
 [[151.28053]
 [184.83565]
 [180.4152 ]
 [199.1588 ]
 [139.36746]
 [106.94492]
 [151.99124]
 [116.72742]
 [176.55977]
 [169.52385]
 [144.58382]
 [144.825  ]
 [183.78574]
 [149.11768]
 [153.41188]
 [189.80148]
 [139.69987]
 [183.52316]
 [174.3236 ]
 [156.07172]
 [177.83124]
 [175.72887]
 [168.52763]
 [146.41273]
 [189.89952]]
1020 Cost:  11.604929 
Prediction:
 [[151.28888]
 [184.83348]
 [180.41978]
 [199.15852]
 [139.36713]
 [106.93509]
 [151.9866 ]
 [116.71814]
 [176.54846]
 [169.50061]
 [144.58113]
 [144.81494]
 [183.79567]
 [149.13264]
 [153.4048 ]
 [189.79538]
 [139.71677]
 [183.51707]
 [174.

1260 Cost:  10.573586 
Prediction:
 [[151.4776 ]
 [184.78532]
 [180.52396]
 [199.15184]
 [139.36107]
 [106.71294]
 [151.87994]
 [116.50513]
 [176.29279]
 [168.97354]
 [144.51978]
 [144.58698]
 [184.02156]
 [149.47377]
 [153.24329]
 [189.6574 ]
 [140.1022 ]
 [183.37701]
 [174.6126 ]
 [156.33855]
 [177.70422]
 [175.57753]
 [168.46661]
 [146.89978]
 [189.95161]]
1270 Cost:  10.535083 
Prediction:
 [[151.48499 ]
 [184.78348 ]
 [180.52805 ]
 [199.15155 ]
 [139.36089 ]
 [106.704216]
 [151.87569 ]
 [116.49665 ]
 [176.28276 ]
 [168.95279 ]
 [144.51733 ]
 [144.578   ]
 [184.03046 ]
 [149.48724 ]
 [153.23688 ]
 [189.65196 ]
 [140.11745 ]
 [183.3714  ]
 [174.62349 ]
 [156.3486  ]
 [177.69937 ]
 [175.57184 ]
 [168.46426 ]
 [146.91815 ]
 [189.95361 ]]
1280 Cost:  10.496884 
Prediction:
 [[151.49237 ]
 [184.78163 ]
 [180.53215 ]
 [199.15129 ]
 [139.36073 ]
 [106.69553 ]
 [151.87144 ]
 [116.488174]
 [176.2728  ]
 [168.93214 ]
 [144.51492 ]
 [144.56909 ]
 [184.03935 ]
 [149.50067 ]
 [153.2305  ]
 [189

1520 Cost:  9.672859 
Prediction:
 [[151.65883]
 [184.7407 ]
 [180.62488]
 [199.1447 ]
 [139.35828]
 [106.49936]
 [151.77394]
 [116.29367]
 [176.04704]
 [168.46352]
 [144.45964]
 [144.36691]
 [184.24121]
 [149.8062 ]
 [153.08463]
 [189.52473]
 [140.4795 ]
 [183.23679]
 [174.88104]
 [156.58583]
 [177.584  ]
 [175.43808]
 [168.40762]
 [147.3519 ]
 [190.00182]]
1530 Cost:  9.642077 
Prediction:
 [[151.66537]
 [184.73914]
 [180.62854]
 [199.14444]
 [139.35825]
 [106.49166]
 [151.77007]
 [116.28592]
 [176.03821]
 [168.44508]
 [144.45747]
 [144.35898]
 [184.24919]
 [149.81827]
 [153.07886]
 [189.51996]
 [140.49327]
 [183.23163]
 [174.89078]
 [156.59479]
 [177.57962]
 [175.43306]
 [168.40546]
 [147.36827]
 [190.0037 ]]
1540 Cost:  9.611574 
Prediction:
 [[151.67184]
 [184.73758]
 [180.63219]
 [199.14417]
 [139.35822]
 [106.48401]
 [151.76619]
 [116.27818]
 [176.0294 ]
 [168.42673]
 [144.45529]
 [144.35107]
 [184.25713]
 [149.83029]
 [153.07309]
 [189.5152 ]
 [140.50694]
 [183.22647]
 [174.900

1780 Cost:  8.952729 
Prediction:
 [[151.81862]
 [184.70299]
 [180.71477]
 [199.13771]
 [139.35884]
 [106.31085]
 [151.67703]
 [116.10047]
 [175.83023]
 [168.01015]
 [144.4055 ]
 [144.17186]
 [184.43758]
 [150.10402]
 [152.94131]
 [189.40767]
 [140.81923]
 [183.10756]
 [175.1203 ]
 [156.8057 ]
 [177.47478]
 [175.31493]
 [168.35287]
 [147.75456]
 [190.0483 ]]
1790 Cost:  8.9281225 
Prediction:
 [[151.82436]
 [184.70166]
 [180.71803]
 [199.13745]
 [139.35892]
 [106.30407]
 [151.67348]
 [116.0934 ]
 [175.82243]
 [167.99376]
 [144.40353]
 [144.16481]
 [184.44469]
 [150.11482]
 [152.93608]
 [189.40344]
 [140.8316 ]
 [183.1028 ]
 [175.12895]
 [156.81364]
 [177.4708 ]
 [175.31047]
 [168.35085]
 [147.76913]
 [190.05003]]
1800 Cost:  8.903714 
Prediction:
 [[151.83008 ]
 [184.70033 ]
 [180.72127 ]
 [199.13718 ]
 [139.35901 ]
 [106.297295]
 [151.66992 ]
 [116.08633 ]
 [175.81467 ]
 [167.97745 ]
 [144.40158 ]
 [144.1578  ]
 [184.45178 ]
 [150.1256  ]
 [152.93088 ]
 [189.39926 ]
 [140.84392 ]
 [18

# Data Load

In [13]:
import tensorflow as tf
import numpy as np

xy = np.loadtxt('/Users/Baobab/Desktop/DeepLearning/DeepLearningZeroToAll/data-01-test-score.csv', 
                delimiter = ',', dtype=np.float32)

In [17]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]
# Shape 와 data 확인
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [20]:
# Placeholder
X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')
# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Cost function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Optimizer
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()
# variable 초기화
sess.run(tf.global_variables_initializer())
# run
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
        

0 Cost:  158.4311 
Prediction:
 [[136.38611]
 [175.27924]
 [166.55571]
 [184.97906]
 [133.54932]
 [105.33797]
 [140.62354]
 [106.9304 ]
 [170.8362 ]
 [167.1913 ]
 [135.18478]
 [139.68642]
 [168.59824]
 [135.79144]
 [143.36444]
 [180.23868]
 [128.49219]
 [168.3887 ]
 [158.4152 ]
 [141.16954]
 [165.25069]
 [167.21492]
 [155.5685 ]
 [129.36862]
 [178.18062]]
10 Cost:  36.360218 
Prediction:
 [[146.71754]
 [187.6535 ]
 [178.7714 ]
 [198.2722 ]
 [142.98477]
 [112.27283]
 [150.57016]
 [114.30024]
 [182.37778]
 [177.85419]
 [144.76595]
 [149.11049]
 [181.22888]
 [146.30357]
 [153.34917]
 [192.78946]
 [138.50314]
 [180.32889]
 [170.46506]
 [151.95403]
 [176.91228]
 [178.81601]
 [166.6936 ]
 [139.80905]
 [191.01692]]
20 Cost:  36.090668 
Prediction:
 [[146.8145 ]
 [187.72704]
 [178.86685]
 [198.36557]
 [143.03891]
 [112.29135]
 [150.63635]
 [114.34538]
 [182.42354]
 [177.86926]
 [144.82779]
 [149.14842]
 [181.33762]
 [146.40622]
 [153.40804]
 [192.85794]
 [138.60043]
 [180.41159]
 [170.57703]
 

250 Cost:  30.624304 
Prediction:
 [[147.37752]
 [187.4633 ]
 [179.11064]
 [198.40001]
 [142.79456]
 [111.64461]
 [150.5823 ]
 [114.22159]
 [181.67653]
 [176.58243]
 [144.73262]
 [148.55095]
 [181.80931]
 [147.06514]
 [153.1877 ]
 [192.45705]
 [139.21654]
 [180.41895]
 [171.20828]
 [152.68156]
 [176.87141]
 [178.46468]
 [166.80685]
 [141.01463]
 [191.0879 ]]
260 Cost:  30.41086 
Prediction:
 [[147.40073]
 [187.45235]
 [179.12065]
 [198.40141]
 [142.78438]
 [111.6179 ]
 [150.58012]
 [114.21659]
 [181.64566]
 [176.52936]
 [144.7287 ]
 [148.5263 ]
 [181.8287 ]
 [147.09221]
 [153.17865]
 [192.44048]
 [139.2418 ]
 [180.41933]
 [171.23425]
 [152.7073 ]
 [176.86665]
 [178.44762]
 [166.80833]
 [141.05927]
 [191.08713]]
270 Cost:  30.19928 
Prediction:
 [[147.42386 ]
 [187.44145 ]
 [179.13065 ]
 [198.40283 ]
 [142.77425 ]
 [111.59131 ]
 [150.57797 ]
 [114.211655]
 [181.61496 ]
 [176.47653 ]
 [144.7248  ]
 [148.50175 ]
 [181.84802 ]
 [147.11917 ]
 [153.16966 ]
 [192.42398 ]
 [139.26695 ]
 [180.4

500 Cost:  25.813293 
Prediction:
 [[147.92924 ]
 [187.20251 ]
 [179.34831 ]
 [198.4339  ]
 [142.55151 ]
 [111.01015 ]
 [150.53224 ]
 [114.106415]
 [180.9435  ]
 [175.32347 ]
 [144.63997 ]
 [147.96559 ]
 [182.26875 ]
 [147.70627 ]
 [152.97449 ]
 [192.0634  ]
 [139.81346 ]
 [180.4311  ]
 [171.82433 ]
 [153.29193 ]
 [176.76021 ]
 [178.05959 ]
 [166.84326 ]
 [142.07349 ]
 [191.06854 ]]
510 Cost:  25.642002 
Prediction:
 [[147.95012 ]
 [187.19261 ]
 [179.3573  ]
 [198.4352  ]
 [142.54225 ]
 [110.98616 ]
 [150.53044 ]
 [114.102196]
 [180.9158  ]
 [175.27596 ]
 [144.63649 ]
 [147.94348 ]
 [182.28609 ]
 [147.73044 ]
 [152.9665  ]
 [192.04854 ]
 [139.83589 ]
 [180.43169 ]
 [171.84758 ]
 [153.31499 ]
 [176.75609 ]
 [178.04427 ]
 [166.84471 ]
 [142.11345 ]
 [191.06776 ]]
520 Cost:  25.472235 
Prediction:
 [[147.97087]
 [187.18274]
 [179.3662 ]
 [198.43646]
 [142.53302]
 [110.96227]
 [150.52861]
 [114.09801]
 [180.88818]
 [175.22859]
 [144.63301]
 [147.92145]
 [182.3033 ]
 [147.75444]
 [152.95853

760 Cost:  21.814856 
Prediction:
 [[148.44377]
 [186.95767]
 [179.56906]
 [198.4662 ]
 [142.32181]
 [110.41864]
 [150.48906]
 [114.00579]
 [180.26012]
 [174.15318]
 [144.55472]
 [147.42076]
 [182.69452]
 [148.2994 ]
 [152.77911]
 [191.69644]
 [140.36298]
 [180.44807]
 [172.39624]
 [153.85928]
 [176.65979]
 [177.68207]
 [166.87997]
 [143.05682]
 [191.04825]]
770 Cost:  21.678596 
Prediction:
 [[148.46243]
 [186.94878]
 [179.57706]
 [198.46738]
 [142.31343]
 [110.39719]
 [150.48758]
 [114.00228]
 [180.23532]
 [174.11081]
 [144.55165]
 [147.40102]
 [182.7099 ]
 [148.32083]
 [152.77211]
 [191.68314]
 [140.38278]
 [180.44882]
 [172.41695]
 [153.87982]
 [176.6562 ]
 [177.66837]
 [166.88136]
 [143.09244]
 [191.04749]]
780 Cost:  21.543484 
Prediction:
 [[148.48102]
 [186.93988]
 [179.58499]
 [198.46857]
 [142.30505]
 [110.37582]
 [150.48608]
 [113.99879]
 [180.21062]
 [174.06859]
 [144.54858]
 [147.38135]
 [182.72522]
 [148.34215]
 [152.7651 ]
 [191.66988]
 [140.40248]
 [180.44954]
 [172.437

 [191.02881 ]]
1020 Cost:  18.633297 
Prediction:
 [[148.90422]
 [186.73706]
 [179.76575]
 [198.49582]
 [142.11339]
 [109.88947]
 [150.45375]
 [113.92219]
 [179.6487 ]
 [173.10947]
 [144.47952]
 [146.9342 ]
 [183.073  ]
 [148.82565]
 [152.60757]
 [191.36816]
 [140.84804]
 [180.46864]
 [172.90561]
 [154.36526]
 [176.57301]
 [177.34444]
 [166.91547]
 [143.93297]
 [191.02802]]
1030 Cost:  18.524834 
Prediction:
 [[148.92093]
 [186.72902]
 [179.77289]
 [198.4969 ]
 [142.10576]
 [109.87026]
 [150.45253]
 [113.91927]
 [179.62653]
 [173.07166]
 [144.4768 ]
 [146.91656]
 [183.08667]
 [148.84467]
 [152.60141]
 [191.35625]
 [140.86551]
 [180.46951]
 [172.92404]
 [154.3836 ]
 [176.56995]
 [177.3322 ]
 [166.91681]
 [143.96468]
 [191.02724]]
1040 Cost:  18.417334 
Prediction:
 [[148.93758 ]
 [186.72101 ]
 [179.77998 ]
 [198.49799 ]
 [142.09818 ]
 [109.85116 ]
 [150.45132 ]
 [113.916405]
 [179.60443 ]
 [173.03401 ]
 [144.47412 ]
 [146.89902 ]
 [183.1003  ]
 [148.86359 ]
 [152.59529 ]
 [191.34439 ]
 

1270 Cost:  16.188112 
Prediction:
 [[149.30133 ]
 [186.54543 ]
 [179.93466 ]
 [198.52194 ]
 [141.93106 ]
 [109.43321 ]
 [150.42622 ]
 [113.855774]
 [179.12152 ]
 [172.2124  ]
 [144.41562 ]
 [146.51546 ]
 [183.39716 ]
 [149.27553 ]
 [152.46252 ]
 [191.08514 ]
 [141.2604  ]
 [180.49113 ]
 [173.34276 ]
 [154.80014 ]
 [176.50095 ]
 [177.05347 ]
 [166.94843 ]
 [144.68518 ]
 [191.0087  ]]
1280 Cost:  16.101027 
Prediction:
 [[149.31636 ]
 [186.53813 ]
 [179.94102 ]
 [198.52293 ]
 [141.9241  ]
 [109.415955]
 [150.42523 ]
 [113.85338 ]
 [179.10158 ]
 [172.17853 ]
 [144.41321 ]
 [146.49963 ]
 [183.40936 ]
 [149.29247 ]
 [152.45708 ]
 [191.07443 ]
 [141.27588 ]
 [180.49207 ]
 [173.35925 ]
 [154.81654 ]
 [176.49828 ]
 [177.04245 ]
 [166.9497  ]
 [144.71355 ]
 [191.00792 ]]
1290 Cost:  16.014692 
Prediction:
 [[149.33134 ]
 [186.53091 ]
 [179.9474  ]
 [198.52396 ]
 [141.9172  ]
 [109.39877 ]
 [150.42429 ]
 [113.851006]
 [179.08176 ]
 [172.14484 ]
 [144.41084 ]
 [146.4839  ]
 [183.42155 ]
 [149.30

1530 Cost:  14.154328 
Prediction:
 [[149.67192]
 [186.36531]
 [180.09154]
 [198.54694]
 [141.75847]
 [109.00761]
 [150.4034 ]
 [113.79934]
 [178.62976]
 [171.37843]
 [144.35695]
 [146.1256 ]
 [183.69748]
 [149.69145]
 [152.32999]
 [190.82115]
 [141.63942]
 [180.51674]
 [173.74858]
 [155.20444]
 [176.43636]
 [176.78214]
 [166.98143]
 [145.38377]
 [190.98888]]
1540 Cost:  14.084974 
Prediction:
 [[149.6854  ]
 [186.35875 ]
 [180.09724 ]
 [198.54788 ]
 [141.75217 ]
 [108.992165]
 [150.40263 ]
 [113.7974  ]
 [178.61192 ]
 [171.34824 ]
 [144.35484 ]
 [146.11147 ]
 [183.70834 ]
 [149.70648 ]
 [152.32526 ]
 [190.8116  ]
 [141.65308 ]
 [180.51776 ]
 [173.76328 ]
 [155.2191  ]
 [176.4341  ]
 [176.77231 ]
 [166.9827  ]
 [145.40907 ]
 [190.98813 ]]
1550 Cost:  14.016235 
Prediction:
 [[149.69878]
 [186.35222]
 [180.1029 ]
 [198.5488 ]
 [141.74586]
 [108.97678]
 [150.40187]
 [113.79549]
 [178.59416]
 [171.31816]
 [144.35275]
 [146.0974 ]
 [183.71915]
 [149.72144]
 [152.32053]
 [190.80206]
 [141.6

1800 Cost:  12.479354 
Prediction:
 [[150.01582]
 [186.19685]
 [180.23642]
 [198.57074]
 [141.59584]
 [108.61278]
 [150.38509]
 [113.7525 ]
 [178.17357]
 [170.60757]
 [144.30345]
 [145.76468]
 [183.97398]
 [150.07353]
 [152.20985]
 [190.57631]
 [141.98535]
 [180.54514]
 [174.1231 ]
 [155.57816]
 [176.37914]
 [176.53058]
 [167.01436]
 [146.02876]
 [190.96869]]
1810 Cost:  12.424596 
Prediction:
 [[150.02782]
 [186.19093]
 [180.24147]
 [198.57158]
 [141.5901 ]
 [108.59901]
 [150.38449]
 [113.75097]
 [178.15765]
 [170.58073]
 [144.30159]
 [145.75209]
 [183.98358]
 [150.08678]
 [152.2057 ]
 [190.56776]
 [141.9973 ]
 [180.54619]
 [174.1361 ]
 [155.59116]
 [176.37718]
 [176.52179]
 [167.01555]
 [146.05118]
 [190.96794]]
1820 Cost:  12.370306 
Prediction:
 [[150.03976]
 [186.18507]
 [180.24649]
 [198.57242]
 [141.58441]
 [108.5853 ]
 [150.38391]
 [113.74946]
 [178.14182]
 [170.55403]
 [144.29976]
 [145.73958]
 [183.99315]
 [150.09998]
 [152.2016 ]
 [190.55927]
 [142.00922]
 [180.5473 ]
 [174.

In [21]:
# My score prediction
print("Your score will be ", sess.run(hypothesis, feed_dict={X:[[100,70,101]]}))
print("Other score will be ", sess.run(hypothesis, feed_dict={X:[[60,70,110],[90,100,80]]}))

Your score will be  [[198.39615]]
Other score will be  [[191.78479]
 [167.93242]]


# Queue Runners

In [26]:
import tensorflow as tf

filename_queue = tf.train.string_input_producer(['/Users/Baobab/Desktop/DeepLearning/DeepLearningZeroToAll/data-01-test-score.csv'],
                                               shuffle=False, name='filename_queue')
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

In [29]:
# Default values, decode result
record_defaults = [[0.], [0.], [0.], [0.]] # 이러한 형태로 읽는다.
xy = tf.decode_csv(value, record_defaults=record_defaults)

# collect batches
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10) # 10개씩 batch한다.
    
# Placeholder
X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X , W) + b

# Cost Function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize 
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [31]:
# Launch the Graph
sess = tf.Session()
# Initialize variables
sess.run(tf.global_variables_initializer())

# Start populating the filename queue
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_batch, Y:y_batch})
    if step % 10 == 0: 
        print(step, "Cost: ", cost_val,
             "\nPrediction:\n", hy_val)
        
coord.request_stop()
coord.join(threads)

0 Cost:  21387.217 
Prediction:
 [[1.7234215]
 [3.428837 ]
 [4.43786  ]
 [2.937422 ]
 [6.412211 ]
 [3.599807 ]
 [5.1743608]
 [4.165543 ]
 [1.3909839]
 [2.1003668]]
10 Cost:  6.3959556 
Prediction:
 [[174.08487]
 [163.18063]
 [142.43484]
 [142.07486]
 [185.44986]
 [153.26134]
 [148.92784]
 [187.70435]
 [145.97937]
 [177.06802]]
20 Cost:  5.815072 
Prediction:
 [[175.28006]
 [164.29091]
 [143.42735]
 [143.05202]
 [186.75136]
 [154.34056]
 [149.96548]
 [189.00313]
 [147.00368]
 [178.31041]]
30 Cost:  5.811967 
Prediction:
 [[175.28621]
 [164.29977]
 [143.4354 ]
 [143.05835]
 [186.7579 ]
 [154.34332]
 [149.9766 ]
 [189.01093]
 [147.00278]
 [178.32654]]
40 Cost:  5.8040123 
Prediction:
 [[175.28426]
 [164.3011 ]
 [143.43669]
 [143.05804]
 [186.75563]
 [154.33875]
 [149.98067]
 [189.00993]
 [146.99489]
 [178.33429]]
50 Cost:  5.796147 
Prediction:
 [[175.28226]
 [164.30237]
 [143.43794]
 [143.05771]
 [186.75333]
 [154.33415]
 [149.98471]
 [189.00887]
 [146.987  ]
 [178.34195]]
60 Cost:  5.78

530 Cost:  5.476823 
Prediction:
 [[175.18816]
 [164.35388]
 [143.49408]
 [143.0395 ]
 [186.65076]
 [154.12991]
 [150.16539]
 [188.95886]
 [146.63368]
 [178.68805]]
540 Cost:  5.471287 
Prediction:
 [[175.18623]
 [164.35477]
 [143.49515]
 [143.03908]
 [186.64879]
 [154.12596]
 [150.1689 ]
 [188.95784]
 [146.62682]
 [178.6948 ]]
550 Cost:  5.4657836 
Prediction:
 [[175.18431]
 [164.35564]
 [143.49622]
 [143.03867]
 [186.64682]
 [154.12204]
 [150.1724 ]
 [188.95682]
 [146.62   ]
 [178.70154]]
560 Cost:  5.4603415 
Prediction:
 [[175.18242]
 [164.3565 ]
 [143.4973 ]
 [143.03825]
 [186.64487]
 [154.11815]
 [150.17589]
 [188.95581]
 [146.61317]
 [178.70827]]
570 Cost:  5.454939 
Prediction:
 [[175.18051]
 [164.35738]
 [143.4984 ]
 [143.03783]
 [186.64293]
 [154.11424]
 [150.17937]
 [188.95479]
 [146.6064 ]
 [178.71498]]
580 Cost:  5.4495497 
Prediction:
 [[175.1786 ]
 [164.35823]
 [143.49945]
 [143.03741]
 [186.64099]
 [154.11035]
 [150.18283]
 [188.95378]
 [146.59961]
 [178.72168]]
590 Cos

1060 Cost:  5.234378 
Prediction:
 [[175.08968]
 [164.3918 ]
 [143.54732]
 [143.01607]
 [186.55511]
 [153.9374 ]
 [150.33835]
 [188.90633]
 [146.29616]
 [179.02348]]
1070 Cost:  5.230689 
Prediction:
 [[175.08789]
 [164.39236]
 [143.54825]
 [143.0156 ]
 [186.55347]
 [153.93405]
 [150.34137]
 [188.90536]
 [146.29025]
 [179.02939]]
1080 Cost:  5.227051 
Prediction:
 [[175.08609]
 [164.39291]
 [143.54918]
 [143.01514]
 [186.55183]
 [153.93073]
 [150.34438]
 [188.9044 ]
 [146.28438]
 [179.03526]]
1090 Cost:  5.2234178 
Prediction:
 [[175.08429]
 [164.39346]
 [143.55008]
 [143.01468]
 [186.55019]
 [153.9274 ]
 [150.34738]
 [188.90343]
 [146.2785 ]
 [179.04114]]
1100 Cost:  5.219831 
Prediction:
 [[175.08252]
 [164.39401]
 [143.55103]
 [143.01422]
 [186.54857]
 [153.9241 ]
 [150.35039]
 [188.9025 ]
 [146.27269]
 [179.047  ]]
1110 Cost:  5.2162447 
Prediction:
 [[175.08073]
 [164.39455]
 [143.55193]
 [143.01375]
 [186.54694]
 [153.92079]
 [150.35338]
 [188.90154]
 [146.26686]
 [179.05284]]
11

1610 Cost:  5.070753 
Prediction:
 [[174.99442]
 [164.41554]
 [143.59442]
 [142.98987]
 [186.47208]
 [153.76828]
 [150.49265]
 [188.85529]
 [145.99564]
 [179.32645]]
1620 Cost:  5.0684137 
Prediction:
 [[174.99275]
 [164.41585]
 [143.5952 ]
 [142.98936]
 [186.47069]
 [153.76546]
 [150.49522]
 [188.85439]
 [145.9906 ]
 [179.33156]]
1630 Cost:  5.0661263 
Prediction:
 [[174.99109]
 [164.41617]
 [143.59598]
 [142.98889]
 [186.46933]
 [153.76266]
 [150.49782]
 [188.8535 ]
 [145.98557]
 [179.33667]]
1640 Cost:  5.0638533 
Prediction:
 [[174.98944]
 [164.41647]
 [143.59677]
 [142.9884 ]
 [186.46797]
 [153.75986]
 [150.50041]
 [188.85262]
 [145.98056]
 [179.34177]]
1650 Cost:  5.0615687 
Prediction:
 [[174.98776]
 [164.41676]
 [143.59753]
 [142.9879 ]
 [186.46658]
 [153.75705]
 [150.50296]
 [188.85172]
 [145.97554]
 [179.34683]]
1660 Cost:  5.0593247 
Prediction:
 [[174.98613]
 [164.41707]
 [143.59831]
 [142.98741]
 [186.46524]
 [153.75427]
 [150.50552]
 [188.85083]
 [145.97057]
 [179.35191]]